sudo: required

language: generic

service:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t dlquddnr414/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=ture dlquddnr414/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"